version: "3.8"

services:
  mongodb:
    image: mongo:4.4-bionic
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=pokedex
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
    restart: always
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27018:27017
    networks:
      - web_api

networks:
  web_api:
    driver: bridge